In [1]:
import torch
from torch.nn import Linear, ReLU
import torch.nn as nn
import numpy as np
from torch.autograd import Variable

In [2]:
myLayer = Linear(in_features=10,out_features=5,bias=True) # 輸入特徵數為 10，輸出特徵數為 5，並啟用偏差（bias）
inp = Variable(torch.randn(1,10))
myLayer(inp) # 執行線性轉換

tensor([[ 0.3442,  1.3424, -0.0624, -0.2083, -0.6045]],
       grad_fn=<AddmmBackward0>)

In [3]:
myLayer.weight

Parameter containing:
tensor([[-0.0388, -0.2929, -0.0886,  0.2930,  0.2227, -0.1821, -0.2815, -0.0637,
         -0.2247,  0.2648],
        [ 0.2461, -0.0985, -0.2300,  0.1556, -0.0641, -0.1608,  0.0818,  0.2959,
         -0.2484,  0.1862],
        [ 0.1704, -0.1136, -0.1565, -0.2362,  0.1928, -0.1212, -0.0436, -0.2342,
         -0.2410,  0.0882],
        [-0.0122,  0.1800, -0.0034, -0.0599,  0.2724,  0.1632, -0.1307, -0.0951,
          0.2645, -0.0450],
        [ 0.0702, -0.0760, -0.0509,  0.2062,  0.2856,  0.3123, -0.3155,  0.1065,
         -0.1144, -0.1153]], requires_grad=True)

In [4]:
myLayer.bias

Parameter containing:
tensor([ 0.2805,  0.0407, -0.2590, -0.1784, -0.2585], requires_grad=True)

In [5]:
myLayer1 = Linear(10,5) # 輸入特徵數為 10，輸出特徵數為 5 
myLayer2 = Linear(5,2) # 要進入下一層需要符合上一層輸出特徵數
myLayer2(myLayer1(inp))

tensor([[0.1616, 0.2674]], grad_fn=<AddmmBackward0>)

In [8]:
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
myRelu = ReLU()
myRelu(sample_data) #  使用ReLU函數，負值將取為0，正值則不變

tensor([[1., 2., 0., 0.]])

In [9]:
import torch.nn.functional as F
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
f = F.relu(sample_data) # Much simpler.
f

tensor([[1., 2., 0., 0.]])

In [12]:
class MyFirstNetwork(nn.Module):
    def __init__(self,input_size,hidden_size,output_size):
        super(MyFirstNetwork,self).__init__() 
        self.layer1 = nn.Linear(input_size,hidden_size) # 透過這兩個線性層，模型可以學習從輸入到輸出的映射。在每一層之間，使用 ReLU 激活函數（torch.relu）來引入非線性。
        self.layer2 = nn.Linear(hidden_size,output_size)
    def __forward__(self,input): 
        out = self.layer1(input) # 執行了線性轉換操作，將輸入資料映射到隱藏層（hidden layer）的空間。
        out = nn.ReLU(out)
        out = self.layer2(out) 
        return out

In [13]:
loss = nn.MSELoss() # 創建一個均方誤差的損失函數，並將其存儲在 loss 變數中。
input = Variable(torch.randn(3, 5), requires_grad=True)
target = Variable(torch.randn(3, 5))
output = loss(input, target) # 計算模型輸出 (input) 與目標值 (target) 之間的均方誤差損失。
output.backward() # 執行反向傳播，計算損失對於輸入變數 input 的梯度。這將使得 input 中的 requires_grad 為 True 的元素具有相對於損失的梯度值。

In [14]:
def cross_entropy(true_label, prediction): # 計算交叉熵損失
    if true_label == 1:
        return -log(prediction)
    else:
        return -log(1 - prediction)

In [15]:
loss = nn.CrossEntropyLoss()
input = Variable(torch.randn(3, 5), requires_grad=True) 
target = Variable(torch.LongTensor(3).random_(5)) 
output = loss(input, target)
output.backward()